### ISSUE TITLE
文档中有一些语法错误

### ISSUE THREAD

**Issue by afc163** [antvis/L7#160]
npm start 后命令行输出可见：

```
 ERROR 

error formatting block SyntaxError: Unexpected token, expected "," (15:4)
  13 |         }
  14 |       ],
> 15 |   }
     |    ^
    at e (/Users/afc163/Projects/L7/node_modules/prettier/parser-babylon.js:1:344)
    at Object.parse (/Users/afc163/Projects/L7/node_modules/prettier/parser-babylon.js:1:262322)
    at Object.parse (/Users/afc163/Projects/L7/node_modules/prettier/index.js:9739:19)
    at coreFormat (/Users/afc163/Projects/L7/node_modules/prettier/index.js:13252:23)
    at format (/Users/afc163/Projects/L7/node_modules/prettier/index.js:13510:73)
    at formatWithCursor (/Users/afc163/Projects/L7/node_modules/prettier/index.js:13526:12)
    at /Users/afc163/Projects/L7/node_modules/prettier/index.js:44207:15
    at Object.format (/Users/afc163/Projects/L7/node_modules/prettier/index.js:44226:12)
    at /Users/afc163/Projects/L7/node_modules/gatsby-remark-prettier/index.js:20:36
    at overload (/Users/afc163/Projects/L7/node_modules/unist-util-visit/index.js:27:12)
    at one (/Users/afc163/Projects/L7/node_modules/unist-util-visit-parents/index.js:34:25)
    at all (/Users/afc163/Projects/L7/node_modules/unist-util-visit-parents/index.js:57:16)
    at one (/Users/afc163/Projects/L7/node_modules/unist-util-visit-parents/index.js:42:28)
    at visitParents (/Users/afc163/Projects/L7/node_modules/unist-util-visit-parents/index.js:26:3)
    at visit (/Users/afc163/Projects/L7/node_modules/unist-util-visit/index.js:22:3)
    at /Users/afc163/Projects/L7/node_modules/gatsby-remark-prettier/index.js:11:5 {
  loc: { start: { line: 15, column: 4 } },
  codeFrame: '\u001b[0m \u001b[90m 13 | \u001b[39m        }\u001b[0m\n' +
    '\u001b[0m \u001b[90m 14 | \u001b[39m      ]\u001b[33m,\u001b[39m\u001b[0m\n' +
    '\u001b[0m\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m 15 | \u001b[39m  }\u001b[0m\n' +
    '\u001b[0m \u001b[90m    | \u001b[39m   \u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[0m'
}


 ERROR 

error formatting block SyntaxError: Unexpected token, expected "," (15:4)
  13 |         }
  14 |       ],
> 15 |   }
     |    ^
    at e (/Users/afc163/Projects/L7/node_modules/prettier/parser-babylon.js:1:344)
    at Object.parse (/Users/afc163/Projects/L7/node_modules/prettier/parser-babylon.js:1:262322)
    at Object.parse (/Users/afc163/Projects/L7/node_modules/prettier/index.js:9739:19)
    at coreFormat (/Users/afc163/Projects/L7/node_modules/prettier/index.js:13252:23)
    at format (/Users/afc163/Projects/L7/node_modules/prettier/index.js:13510:73)
    at formatWithCursor (/Users/afc163/Projects/L7/node_modules/prettier/index.js:13526:12)
    at /Users/afc163/Projects/L7/node_modules/prettier/index.js:44207:15
    at Object.format (/Users/afc163/Projects/L7/node_modules/prettier/index.js:44226:12)
    at /Users/afc163/Projects/L7/node_modules/gatsby-remark-prettier/index.js:20:36
    at overload (/Users/afc163/Projects/L7/node_modules/unist-util-visit/index.js:27:12)
    at one (/Users/afc163/Projects/L7/node_modules/unist-util-visit-parents/index.js:34:25)
    at all (/Users/afc163/Projects/L7/node_modules/unist-util-visit-parents/index.js:57:16)
    at one (/Users/afc163/Projects/L7/node_modules/unist-util-visit-parents/index.js:42:28)
    at visitParents (/Users/afc163/Projects/L7/node_modules/unist-util-visit-parents/index.js:26:3)
    at visit (/Users/afc163/Projects/L7/node_modules/unist-util-visit/index.js:22:3)
    at /Users/afc163/Projects/L7/node_modules/gatsby-remark-prettier/index.js:11:5 {
  loc: { start: { line: 15, column: 4 } },
  codeFrame: '\u001b[0m \u001b[90m 13 | \u001b[39m        }\u001b[0m\n' +
    '\u001b[0m \u001b[90m 14 | \u001b[39m      ]\u001b[33m,\u001b[39m\u001b[0m\n' +
    '\u001b[0m\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m 15 | \u001b[39m  }\u001b[0m\n' +
    '\u001b[0m \u001b[90m    | \u001b[39m   \u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[0m'
}
```

**Comment by lzxue** [comment]
已修复
