### ISSUE TITLE
高德地图加载     scene.on('click', (ev) => {}) 为什么报错误？

### ISSUE THREAD

**Issue by DreamNO1** [antvis/L7#1855]
1.方法   scene.on('click', (ev) => {
              console.log(ev);
             console.log('scene.on click');
            }); 
2. error：
AMapBaseService.js:178 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'on')
    at AMapService.on (AMapBaseService.js:178:1)
    at Scene.on (index.js:457:1)
    at Proxy.InstallMap (GaoDeMapChoropleth.vue:100:1)
    at Proxy.mounted (GaoDeMapChoropleth.vue:20:1)
    at eval (runtime-core.esm-bundler.js:2675:1)
    at callWithErrorHandling (runtime-core.esm-bundler.js:158:1)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:166:1)
    at hook.__weh.hook.__weh (runtime-core.esm-bundler.js:2655:1)
    at flushPostFlushCbs (runtime-core.esm-bundler.js:325:1)
    at flushJobs (runtime-core.esm-bundler.js:363:1)

**Comment by DreamNO1** [comment]
const scene = new Scene({
                id: 'map',
                map: new GaodeMap({
                  style: 'normal',
                  center: [120.19382669582967, 30.258134],
                  zoom: 3,
                }),
              });    

 scene.on('loaded', () => {})  是可以正常加载的，地图也是可以正常加载的

**Comment by lzxue** [comment]
地图没初始化完成，click  放到 loaded 里面去监听，

**Comment by DreamNO1** [comment]
好的，感谢
