### ISSUE TITLE
加载地图 出错误

### ISSUE THREAD

**Issue by DreamNO1** [antvis/L7#1971]
### 问题描述

1.调用方法    const scene = new Scene({
                id: 'map',
                map: new GaodeMap({
                  style: 'light',
                  // center: [120.19382669582967, 30.258134],
                  zoom: 3,
                }),
              });
2.引入
import { GaodeMap, Scene } from '@antv/l7';
import { Choropleth } from '@antv/l7plot';

2.出现的错误 error
Uncaught runtime errors:
×
ERROR
Script error.
    at handleError (webpack-internal:///./node_modules/webpack-dev-server/client/overlay.js:299:58)
    at eval (webpack-internal:///./node_modules/webpack-dev-server/client/overlay.js:318:7)

这是什么情况？

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by DreamNO1** [comment]
Uncaught Error: Invalid Object: LngLat(NaN, NaN)
    at new r (maps?callback=___onAPILoaded&v=2.0&key=ff533602d57df6f8ab3b0fea226ae52f&plugin=Map3D:1:93452)
    at new c (maps?callback=___onAPILoaded&v=2.0&key=ff533602d57df6f8ab3b0fea226ae52f&plugin=Map3D:1:537670)
    at Vt.getData (maps?callback=___onAPILoaded&v=2.0&key=ff533602d57df6f8ab3b0fea226ae52f&plugin=Map3D:1:553122)
    at Gi.getData (maps?callback=___onAPILoaded&v=2.0&key=ff533602d57df6f8ab3b0fea226ae52f&plugin=Map3D:1:591869)
    at e.renderFrame (eval at nS (maps?callback=___onAPILoaded&v=2.0&key=ff533602d57df6f8ab3b0fea226ae52f&plugin=Map3D:1:191041), <anonymous>:1:420475)
    at x.Yf (maps?callback=___onAPILoaded&v=2.0&key=ff533602d57df6f8ab3b0fea226ae52f&plugin=Map3D:1:712843)
    at maps?callback=___onAPILoaded&v=2.0&key=ff533602d57df6f8ab3b0fea226ae52f&plugin=Map3D:1:115966

**Comment by lzxue** [comment]
地图没设置高度

**Comment by DreamNO1** [comment]
好的，感谢已经解决
