### ISSUE TITLE
符号图，通过shape方法修改符号失败

### ISSUE THREAD

**Issue by wlfei0502** [antvis/L7#2167]
### 问题描述

在官网https://l7.antv.antgroup.com/zh/examples/point/image/#weather的示例代码中，增加以下测试代码：
 fetch(
    'https://gw.alipayobjects.com/os/basement_prod/c6042c6b-45fd-4e2e-adf8-fdbf060441e8.json'
  )
    .then(res => res.json())
    .then(data => {
      const imageLayer = new PointLayer()
        .source(data)
        .shape('w')
        .size(15);
      // 测试代码
       setTimeout(() => {
          imageLayer.shape('test')
          scene.render();
       }, 1000) 

       setTimeout(() => {
          imageLayer.shape('05')
          scene.render();
       }, 2000) 
    
      scene.addLayer(imageLayer);
    });
控制台发生异常，修改失败：
umi.eda4a431.js:1 Error: (regl) invalid buffer data
    at Function.r [as raise] (umi.eda4a431.js:1:6486465)
    at p (umi.eda4a431.js:1:6505286)
    at d (umi.eda4a431.js:1:6506731)
    at Object.f [as create] (umi.eda4a431.js:1:6507819)
    at Function.buffer (umi.eda4a431.js:1:6600233)
    at e (umi.eda4a431.js:1:1958480)
    at umi.eda4a431.js:1:2122365
    at umi.eda4a431.js:1:1241304
    at Array.forEach (<anonymous>)
    at e.value (umi.eda4a431.js:1:1241213)
    at umi.eda4a431.js:1:1344875
    at new Promise (<anonymous>)
    at r.<anonymous> (umi.eda4a431.js:1:1344820)
    at f (umi.eda4a431.js:1:7573847)
    at Generator.<anonymous> (umi.eda4a431.js:1:7575174)
    at Generator.next (umi.eda4a431.js:1:7574257)
    at t (umi.eda4a431.js:1:7565660)
    at s (umi.eda4a431.js:1:7565871)
    at umi.eda4a431.js:1:7565930
    at new Promise (<anonymous>)
    at r.<anonymous> (umi.eda4a431.js:1:7565811)
    at r.<anonymous> (umi.eda4a431.js:1:1345262)
    at i.<anonymous> (umi.eda4a431.js:1:1589026)
    at f (umi.eda4a431.js:1:7573847)
    at Generator.<anonymous> (umi.eda4a431.js:1:7575174)
    at Generator.next (umi.eda4a431.js:1:7574257)
    at t (umi.eda4a431.js:1:7565660)
    at s (umi.eda4a431.js:1:7565871)
    at umi.eda4a431.js:1:7565930
    at new Promise (<anonymous>)
    at i.<anonymous> (umi.eda4a431.js:1:7565811)
    at i.<anonymous> (umi.eda4a431.js:1:1591574)
    at i.<anonymous> (umi.eda4a431.js:1:1588613)
    at f (umi.eda4a431.js:1:7573847)
    at Generator.<anonymous> (umi.eda4a431.js:1:7575174)
    at Generator.next (umi.eda4a431.js:1:7574257)
    at t (umi.eda4a431.js:1:7565660)
    at s (umi.eda4a431.js:1:7565871)
    at umi.eda4a431.js:1:7565930
    at new Promise (<anonymous>)
    at i.<anonymous> (umi.eda4a431.js:1:7565811)
    at i.<anonymous> (umi.eda4a431.js:1:1588696)
    at r.<anonymous> (umi.eda4a431.js:1:1348763)
    at f (umi.eda4a431.js:1:7573847)
    at Generator.<anonymous> (umi.eda4a431.js:1:7575174)
    at Generator.next (umi.eda4a431.js:1:7574257)
    at t (umi.eda4a431.js:1:7565660)
    at s (umi.eda4a431.js:1:7565871)
    at umi.eda4a431.js:1:7565930
    at new Promise (<anonymous>)

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by lzxue** [comment]
我在官网验证了一下可以的

**Comment by wlfei0502** [comment]
不知道您是怎么验证的，我是写了两个setTimeout，第一个setTimeout里面的图片名称（test）是随便写的一个，第二个setTimeout里面的图片名称（05）是真实存在的：
// 测试代码
```
setTimeout(() => {
      imageLayer.shape('test')
      scene.render();
}, 1000)

setTimeout(() => {
     imageLayer.shape('05')
     scene.render();
}, 2000) 
```
我这么测试是会报异常的

**Comment by lzxue** [comment]
建议不要写不存在的shape, 你可以提供复现的demo

**Comment by wlfei0502** [comment]
demo地址：
https://codesandbox.io/p/sandbox/vigilant-lovelace-42k9z9?file=%2Findex.js

**Comment by lzxue** [comment]
不要设置不存在的shape，过程中设置了，不存在的shape，导致类型错误，
