### ISSUE TITLE
天地图setCenter方法缺失，仅有centerAndZoom可设置

### ISSUE THREAD

**Issue by Mostrey** [antvis/L7#2383]
### 问题描述

Uncaught (in promise) TypeError: this.map.setCenter is not a function
    at r.value (l7-maps@2.21.0:1:464344)
    at e.value (l7@2.21.0:1:1191809)
    at a.setZoomAndCenter (l7-position-TMap.vue:404:1)
    at o.<anonymous> (l7-position-TMap.vue:253:1)
    at s.emit (l7@2.21.0:1:1362896)
    at e.value (l7@2.21.0:1:141083)
    at l7@2.21.0:1:134339
    at d (l7@2.21.0:1:1634044)
    at Generator.<anonymous> (l7@2.21.0:1:1635371)
    at Generator.next (l7@2.21.0:1:1634454)

### 预期行为

使用天地图centerAndZoom方法替代

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by lzxue** [comment]
可以尝试 scene.map 取到原生map 设置
