### ISSUE TITLE
l7hammerjs ReferenceError: document is not defined

### ISSUE THREAD

**Issue by zhxqc** [antvis/L7#893]
"@antv/l7": "2.6.24",
"@antv/l7-district": "2.3.12",
"@antv/l7-maps": "2.6.24",
"vue": "3.2.26",
"vite": "2.5.10",

SSR项目，项目启动时报错

ReferenceError: document is not defined
    at Object.<anonymous> (/Users/xxx/Documents/WorkSpaces/secnium/asr-ssr-fe/node_modules/l7hammerjs/hammer.js:2666:6)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/Users/xxx/Documents/WorkSpaces/secnium/asr-ssr-fe/node_modules/@antv/l7-core/lib/services/interaction/InteractionService.js:36:42)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)

![image](https://user-images.githubusercontent.com/35363368/147202882-c04abc9d-e443-443d-8250-80d70c103e04.png)

定位到依赖报错代码如下

**Comment by zhxqc** [comment]
本地dev过程偶现，部署到生产环境必现

**Comment by 2912401452** [comment]
好的，感谢反馈

**Comment by 2912401452** [comment]
目前不支持 SSR
